# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_b2csubcriptionplan_b2csubcriptiontier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookedappointment",
            name="applied_free_quick_sparkle",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bookedappointment",
            name="complimentary_quick_sparkle_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("loyalty", "Loyalty"),
                    ("subscription", "Subscription"),
                    ("partner", "Partner referral"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
