# Generated by Django 5.2.17 on 2026-08-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0100_fleet_complimentary_sparkles'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fleetcomplimentarybooking',
            new_name='main_fleetc_fleet_i_8d2232_idx',
            old_name='fleetccomp_fleet_period',
        ),
        migrations.RenameIndex(
            model_name='fleetcomplimentarybooking',
            new_name='main_fleetc_branch__5f220b_idx',
            old_name='fleetccomp_branch_period',
        ),
        migrations.AlterField(
            model_name='bookedappointmentimage',
            name='image_url',
            field=models.URLField(max_length=1000),
        ),
    ]
