# Generated by Django 5.2.17 on 2026-09-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0105_guest_booking_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_guest',
            field=models.BooleanField(db_index=True, default=False, help_text='Shadow checkout account: no password, no loyalty, results via emailed token.'),
        ),
    ]
